### ISSUE TITLE
❓👂 Question/Feedback - Standardizing URLs by Removing Locale Identifiers for Better Accessibility

### ISSUE THREAD

**Issue by noriouch** [Azure/Azure-Proactive-Resiliency-Library-v2#642]
### Description

In `recommendations.yaml`, some URLs include the locale identifier **“en-us”**, while others do not.

When a URL does **not** specify a locale, the displayed language is automatically determined based on the user’s browser settings. However, when a URL **does** specify a locale, the page is always displayed in English, even for non-English speakers.

### Example
File: [Azure-Proactive-Resiliency-Library-v2/azure-waf/reliability/recommendations.yaml](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/azure-waf/reliability/recommendations.yaml)
```
learnMoreLink:
  - name: RE:05 Redundancy
    url: "https://learn.microsoft.com/azure/well-architected/reliability/redundancy"

learnMoreLink:
  - name: RE:05 High-availability multi-region design
    url: "https://learn.microsoft.com/en-us/azure/well-architected/reliability/highly-available-multi-region-design"
```

### Proposed Solution

To improve accessibility for APRL users, many of whom are non-native English speakers, I propose **removing “en-us” from URLs** and standardizing them without explicit locale identifiers.

✅ If the URL does not specify a locale, the appropriate language version will be automatically selected based on the user’s browser settings:
	•	Primary language = English → Redirects to a URL containing **“en-us”**
	•	Primaly language = Japanese → Redirects to a URL containing **“ja-jp”**

This change will provide a more seamless and user-friendly experience for both English and non-English speakers.

### Next Steps

I can create a PR to implement this change if agreed. Let me know your thoughts! 🚀
